baseurl = "/"
languageCode = "en-us"
title = "道法自然"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1
[[menu.main]]
    name = "Life"
    url = "/life/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

[params]
    description = ""
	author = "道道法"
    footer = "&copy; [DDF](http://neojos.com) 2017 | [Github](https://github.com/GitHubSi) | [CSDN](http://blog.csdn.net/whynottrythis) | [segmentfault](https://segmentfault.com/u/neojos)"

  highlightjsVersion = "9.14.1"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex", "go"]
  highlightjsTheme = "googlecode"